name: MegaCMD-Download
on: push
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - name: Preparation
      run: |
       mkdir MegaDownload
    - name: Download
      uses: Difegue/action-megacmd@master
      with:
        args: get https://mega.nz/file/elgzCSCD#93kw336A0BMdwDcv7VGabThVeuK4vcK_FLrDMG_fhfI ./MegaDownload/
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: files
        path: ./MegaDownload
